FROM node:18-alpine3.16

# BUSINESS SERVICES
ARG REACT_APP_INVOICE_SERVICE_ENDPOINT
ARG REACT_APP_INVENTORY_ENDPOINT
ARG REACT_APP_EXPENSE_SERVICE_ENDPOINT
ARG REACT_APP_PROFIT_SERVICE_ENDPOINT
ARG REACT_APP_SERVICE_CLASSIFICATION_ENDPOINT
ARG REACT_APP_RESERVATION_SERVICE_ENDPOINT

ARG WDS_SOCKET_PORT

# FILE SERVICE
ARG REACT_APP_FILE_SERVICE_ENDPOINT
ARG REACT_APP_FILE_SERVICE_PORT
ARG REACT_APP_FILE_SERVICE_SSL_ENABLED
ARG REACT_APP_FILE_SERVICE_ACCESS_KEY
ARG REACT_APP_FILE_SERVICE_SECRET_KEY

WORKDIR /app
COPY . .
# ==== BUILD =====
# Install dependencies (npm ci makes sure the exact versions in the lockfile gets installed)
RUN npm ci 
# Build the app
RUN npm run build
# ==== RUN =======
# Set the env to "production"

ENV NODE_ENV production
ENV REACT_APP_INVOICE_SERVICE_ENDPOINT=$REACT_APP_INVOICE_SERVICE_ENDPOINT
ENV REACT_APP_INVENTORY_ENDPOINT=$REACT_APP_INVENTORY_ENDPOINT
ENV REACT_APP_PROFIT_SERVICE_ENDPOINT=$REACT_APP_PROFIT_SERVICE_ENDPOINT
ENV REACT_APP_EXPENSE_SERVICE_ENDPOINT=$REACT_APP_EXPENSE_SERVICE_ENDPOINT
ENV REACT_APP_SERVICE_CLASSIFICATION_ENDPOINT=$REACT_APP_SERVICE_CLASSIFICATION_ENDPOINT
ENV REACT_APP_RESERVATION_SERVICE_ENDPOINT=$REACT_APP_RESERVATION_SERVICE_ENDPOINT

ENV WDS_SOCKET_PORT=$WDS_SOCKET_PORT

ENV REACT_APP_FILE_SERVICE_ENDPOINT=$REACT_APP_FILE_SERVICE_ENDPOINT
ENV REACT_APP_FILE_SERVICE_PORT=$REACT_APP_FILE_SERVICE_PORT
ENV REACT_APP_FILE_SERVICE_SSL_ENABLED=$REACT_APP_FILE_SERVICE_SSL_ENABLED
ENV REACT_APP_FILE_SERVICE_ACCESS_KEY=$REACT_APP_FILE_SERVICE_ACCESS_KEY
ENV REACT_APP_FILE_SERVICE_SECRET_KEY=$REACT_APP_FILE_SERVICE_SECRET_KEY

# Expose the port on which the app will be running (3000 is the default that `serve` uses)
EXPOSE 3000
# Start the app
ENTRYPOINT [ "npm", "run", "start" ]